version: "3.8"

services:
  app:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: transactions_app
    ports:
      - "8080:8080"
    volumes:
      - ../migrations:/app/migrations:ro
      - ../database.db:/app/database.db
